# fly.toml app configuration file generated for rss-schedule-storage-floral-surf-4703 on 2024-04-20T22:55:44+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'rss-schedule-storage-floral-surf-4703'
primary_region = 'lax'

[build]
  builder = 'paketobuildpacks/builder:base'

[env]
  PORT = '8080'
  INTERVAL_SECONDS="600"
  SHEET_KEY="1hXNLUNliBQTwnbd2fMoF6qxCTWmHn2YFF6zRKSUYDuo"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
